"""Initial database setup

Revision ID: f52126dd83ed
Revises: 
Create Date: 2026-05-06 15:18:47.358947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52126dd83ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_email_address'), ['email_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_members_handle'), ['handle'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peer_a_id', sa.Integer(), nullable=False),
    sa.Column('peer_b_id', sa.Integer(), nullable=False),
    sa.Column('formed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['peer_a_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['peer_b_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('peer_a_id', 'peer_b_id', name='unique_connection')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_peer_a_id'), ['peer_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_peer_b_id'), ['peer_b_id'], unique=False)

    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_messages_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_direct_messages_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('saved_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('bookmarked_member_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bookmarked_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'bookmarked_member_id', name='unique_bookmark')
    )
    with op.batch_alter_table('saved_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_profiles_bookmarked_member_id'), ['bookmarked_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_profiles_owner_id'), ['owner_id'], unique=False)

    op.create_table('swipe_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'target_id', name='unique_swipe')
    )
    with op.batch_alter_table('swipe_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swipe_actions_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_actions_target_id'), ['target_id'], unique=False)

    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('years_old', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('city_area', sa.String(length=100), nullable=True),
    sa.Column('home_parish', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('seeking', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('connection_goal', sa.String(length=50), nullable=True),
    sa.Column('display_picture', sa.String(length=255), nullable=True),
    sa.Column('visibility_status', sa.Boolean(), nullable=True),
    sa.Column('setup_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_details_city_area'), ['city_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_details_years_old'), ['years_old'], unique=False)

    op.create_table('detail_tags_link',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['user_details.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('detail_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_tags_link')
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_details_years_old'))
        batch_op.drop_index(batch_op.f('ix_user_details_city_area'))

    op.drop_table('user_details')
    with op.batch_alter_table('swipe_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swipe_actions_target_id'))
        batch_op.drop_index(batch_op.f('ix_swipe_actions_actor_id'))

    op.drop_table('swipe_actions')
    with op.batch_alter_table('saved_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_profiles_owner_id'))
        batch_op.drop_index(batch_op.f('ix_saved_profiles_bookmarked_member_id'))

    op.drop_table('saved_profiles')
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_direct_messages_author_id'))

    op.drop_table('direct_messages')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_peer_b_id'))
        batch_op.drop_index(batch_op.f('ix_connections_peer_a_id'))

    op.drop_table('connections')
    op.drop_table('tags')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_handle'))
        batch_op.drop_index(batch_op.f('ix_members_email_address'))

    op.drop_table('members')
    # ### end Alembic commands ###
